import { buildStandardProductDescription } from "@/lib/formatters"

export interface Watch {
  id: string
  brand: string
  model: string
  reference: string
  year: number
  condition: "Unworn" | "Excellent" | "Very Good" | "Good"
  price: number
  status: "Available" | "Pending" | "Sold"
  boxAndPapers: boolean
  description: string
  images: string[]
  slug: string
  featured: boolean
  // Scraper integration fields
  externalId?: string
  sourceUrl?: string
  // Display fields (derived)
  diameter?: string
  movement?: string
  caseMaterial?: string
  dialColor?: string
  bracelet?: string
}

const standardDescription = (year: number, reference: string, condition: string, boxAndPapers: boolean) =>
  buildStandardProductDescription({ year, reference, condition, boxAndPapers, status: "Available" })

export const watches: Watch[] = [
  {
    id: "1",
    brand: "Rolex",
    model: "Submariner Date",
    reference: "126610LN",
    year: 2023,
    condition: "Excellent",
    price: 14500,
    status: "Available",
    boxAndPapers: true,
    description: standardDescription(2023, "126610LN", "Excellent", true),
    images: ["/rolex-submariner-luxury-watch-black-dial-steel-bra.jpg"],
    slug: "rolex-submariner-126610ln",
    featured: true,
    diameter: "41mm",
    movement: "Automatic",
    caseMaterial: "Oystersteel",
    dialColor: "Black",
    bracelet: "Oyster",
  },
  {
    id: "2",
    brand: "Patek Philippe",
    model: "Nautilus",
    reference: "5711/1A-010",
    year: 2021,
    condition: "Excellent",
    price: 125000,
    status: "Available",
    boxAndPapers: true,
    description: standardDescription(2021, "5711/1A-010", "Excellent", true),
    images: ["/patek-philippe-nautilus-blue-dial-steel-watch.jpg"],
    slug: "patek-philippe-nautilus-5711-1a-010",
    featured: true,
    diameter: "40mm",
    movement: "Automatic",
    caseMaterial: "Stainless Steel",
    dialColor: "Blue",
    bracelet: "Steel",
  },
  {
    id: "3",
    brand: "Audemars Piguet",
    model: "Royal Oak",
    reference: "15500ST.OO.1220ST.01",
    year: 2022,
    condition: "Very Good",
    price: 42000,
    status: "Pending",
    boxAndPapers: true,
    description: standardDescription(2022, "15500ST.OO.1220ST.01", "Very Good", true),
    images: ["/audemars-piguet-royal-oak-blue-dial-steel-watch.jpg"],
    slug: "audemars-piguet-royal-oak-15500st",
    featured: true,
    diameter: "41mm",
    movement: "Automatic",
    caseMaterial: "Stainless Steel",
    dialColor: "Blue",
    bracelet: "Steel",
  },
  {
    id: "4",
    brand: "Omega",
    model: "Speedmaster Moonwatch",
    reference: "310.30.42.50.01.001",
    year: 2023,
    condition: "Excellent",
    price: 7200,
    status: "Available",
    boxAndPapers: true,
    description: standardDescription(2023, "310.30.42.50.01.001", "Excellent", true),
    images: ["/omega-speedmaster-moonwatch-black-dial-chronograph.jpg"],
    slug: "omega-speedmaster-moonwatch-310-30",
    featured: true,
    diameter: "42mm",
    movement: "Manual",
    caseMaterial: "Stainless Steel",
    dialColor: "Black",
    bracelet: "Steel",
  },
  {
    id: "5",
    brand: "Rolex",
    model: "Daytona",
    reference: "116500LN",
    year: 2022,
    condition: "Excellent",
    price: 32000,
    status: "Sold",
    boxAndPapers: true,
    description: standardDescription(2022, "116500LN", "Excellent", true),
    images: ["/rolex-daytona-white-dial-steel-chronograph-watch.jpg"],
    slug: "rolex-daytona-116500ln",
    featured: false,
    diameter: "40mm",
    movement: "Automatic",
    caseMaterial: "Oystersteel",
    dialColor: "White",
    bracelet: "Oyster",
  },
  {
    id: "6",
    brand: "Rolex",
    model: "GMT-Master II",
    reference: "126710BLRO",
    year: 2023,
    condition: "Excellent",
    price: 19500,
    status: "Available",
    boxAndPapers: true,
    description: standardDescription(2023, "126710BLRO", "Excellent", true),
    images: ["/rolex-gmt-master-ii-pepsi-bezel-jubilee-bracelet.jpg"],
    slug: "rolex-gmt-master-ii-126710blro",
    featured: false,
    diameter: "40mm",
    movement: "Automatic",
    caseMaterial: "Oystersteel",
    dialColor: "Black",
    bracelet: "Jubilee",
  },
  {
    id: "7",
    brand: "Patek Philippe",
    model: "Calatrava",
    reference: "5227G-010",
    year: 2021,
    condition: "Excellent",
    price: 38000,
    status: "Available",
    boxAndPapers: true,
    description: standardDescription(2021, "5227G-010", "Excellent", true),
    images: ["/patek-philippe-calatrava-white-gold-dress-watch.jpg"],
    slug: "patek-philippe-calatrava-5227g-010",
    featured: false,
    diameter: "39mm",
    movement: "Automatic",
    caseMaterial: "White Gold",
    dialColor: "White",
    bracelet: "Leather",
  },
  {
    id: "8",
    brand: "Omega",
    model: "Seamaster 300",
    reference: "210.30.42.20.01.001",
    year: 2022,
    condition: "Very Good",
    price: 5800,
    status: "Available",
    boxAndPapers: true,
    description: standardDescription(2022, "210.30.42.20.01.001", "Very Good", true),
    images: ["/omega-seamaster-300-black-dial-diver-watch.jpg"],
    slug: "omega-seamaster-300-210-30",
    featured: false,
    diameter: "42mm",
    movement: "Automatic",
    caseMaterial: "Stainless Steel",
    dialColor: "Black",
    bracelet: "Steel",
  },
  {
    id: "9",
    brand: "Cartier",
    model: "Santos de Cartier",
    reference: "WSSA0018",
    year: 2023,
    condition: "Excellent",
    price: 8500,
    status: "Pending",
    boxAndPapers: true,
    description: standardDescription(2023, "WSSA0018", "Excellent", true),
    images: ["/cartier-santos-silver-dial-steel-watch.jpg"],
    slug: "cartier-santos-wssa0018",
    featured: false,
    diameter: "39.8mm",
    movement: "Automatic",
    caseMaterial: "Stainless Steel",
    dialColor: "Silver",
    bracelet: "Steel",
  },
  {
    id: "10",
    brand: "Richard Mille",
    model: "RM 011",
    reference: "RM011-FM",
    year: 2020,
    condition: "Excellent",
    price: 185000,
    status: "Available",
    boxAndPapers: true,
    description: standardDescription(2020, "RM011-FM", "Excellent", true),
    images: ["/richard-mille-rm011-skeleton-titanium-watch.jpg"],
    slug: "richard-mille-rm011-fm",
    featured: false,
    diameter: "50mm",
    movement: "Automatic",
    caseMaterial: "Titanium",
    dialColor: "Skeleton",
    bracelet: "Rubber",
  },
  {
    id: "11",
    brand: "Audemars Piguet",
    model: "Royal Oak Offshore",
    reference: "26470ST.OO.A027CA.01",
    year: 2019,
    condition: "Good",
    price: 28000,
    status: "Available",
    boxAndPapers: false,
    description: standardDescription(2019, "26470ST.OO.A027CA.01", "Good", false),
    images: ["/audemars-piguet-royal-oak-offshore-blue-chronograp.jpg"],
    slug: "audemars-piguet-royal-oak-offshore-26470st",
    featured: false,
    diameter: "42mm",
    movement: "Automatic",
    caseMaterial: "Stainless Steel",
    dialColor: "Blue",
    bracelet: "Rubber",
  },
  {
    id: "12",
    brand: "Rolex",
    model: "Datejust 41",
    reference: "126334",
    year: 2023,
    condition: "Excellent",
    price: 12500,
    status: "Available",
    boxAndPapers: true,
    description: standardDescription(2023, "126334", "Excellent", true),
    images: ["/rolex-datejust-41-blue-dial-fluted-bezel-jubilee.jpg"],
    slug: "rolex-datejust-41-126334",
    featured: false,
    diameter: "41mm",
    movement: "Automatic",
    caseMaterial: "Oystersteel & White Gold",
    dialColor: "Blue",
    bracelet: "Jubilee",
  },
]

export const brands = ["Rolex", "Patek Philippe", "Audemars Piguet", "Omega", "Cartier", "Tudor", "Richard Mille"]
export const conditions = ["Unworn", "Excellent", "Very Good", "Good"]
export const statuses = ["Available", "Pending", "Sold"]
